service: car-shows 
provider:
  name: aws
  runtime: nodejs8.10
  region: ap-southeast-2
  environment:
    CARS_API_URL: "http://eacodingtest.digital.energyaustralia.com.au/api/v1/cars"
    FILTER_DATA : "STRICT_VALID"
    
functions:
  get-car-shows:
    handler: handler.getCarShows
    package:
      exclude: spec
    events:
      - http:
          path: car-shows
          method: get
          cors: true
